= High Bleeding Risk Tracker

This repository contains an app that tracks the dynamic bleeding risk of a patient as they present with an acute coronary syndrome, receive a PCI procedure, and spend time as an inpatient under observation, until they are discharged. At that point, their risk is only updated when new information is received about the patient.

The app is structured as a standalone fullstack deployment, intended to be distinct from other hospital systems. It maintains its own database of time-series patient data, which is updated by pulling data automatically from other hospital systems, or by manually inputting data by the clinician.

Bleeding risk is determined by simple calculations based on established risk scores, using data such as the patient age, haemoglobin, platelet count, renal function, and historical ICD-10/OPCS-4 coded patient data.

The primary design goals are:

* To be fast and easy to use.
* To clearly show what is being calculated, including what data may be missing.
* To show how the score changes over time.

Version one will not allow data to be manually inputted. This simplifies the app initially to one that does not require login by a user.

== User Interface

The user interface for the app should have these pages:

* Home page: allows searching for a patient by NHS number
* A patient summary page, with these bits of information:
** **Identity**: Name, NHS number/trust number, Age
** **Scores**: Show the bleeding/ischaemia current scores on the left and right of the page.
*** Below each score, show all current pieces of information used to derive the score. Allow user additions/edits (see below).
* ** Show a simple grid of the components of each score, with green for low risk, red for high risk, or grey for not present.
*** Show a historical graph of the scores.
*** Allow clicking into different elements of information to obtain more information about where the information is from
** **Information for scores**:
*** Current value of the blood counts/other measurements, with a timestamp for each.
*** Graphs showing haemoglobin, platelet count, and eGFR over all time
*** A graph showing bleeding risk score over time

For all values used in the calculation of the risk score, the page should clearly show which are missing. For all pieces of information, it should be possible to modify the value fetched, or add a different value.

NOTE: In this prototype, no data input by the user in the frontend will be saved in the backend. Modifications are only intended to allow clinicians to fix errors and add temporary information to fill out a score.



