# -*- restclient -*-

:host = http://localhost:8000
:patient_id = 7d2b9164-1204-11ef-95f5-0242ac110002

### health
GET :host/health

### create a patient
POST :host/api/v1/patients
Content-Type: application/json

{
    "name": "Joe Bloggs",
    "gender": "male",
    "date_of_birth": "2012-04-23T18:25:43.511Z"
}

### update patient
PUT :host/api/v1/patients
Content-Type: application/json

{
    "id": ":patient_id",
    "gender": "male",
    "name": "John Bloggs"
}

### get all patients
GET :host/api/v1/patients

### get a specific patient
GET :host/api/v1/patients/:patient_id

### get non-existent patient
GET :host/api/v1/patients/356e42a8-e659-406f-98de-eeeeeeeeeeee

### delete patient
DELETE :host/api/v1/patients/:patient_id
