= Backend Design

The backend holds a copy of all patient data used by the application, for the purpose of reliability (no dependency on the functioning of other systems). The information is obtained either automatically from other data sources, or input manually.

Data is provided to the front end via an API interface, which is also how other backend components load data into the system from other sources.

NOTE: This prototype version of the program uses no authentication for simplicity.

The tables stored in the backend are described below in a generic (database independent) way. 

== Patient Table

The patient table is the root of a tree of information about each patient. One row in this table corresponds to one patient. The following data is stored:

[cols="1,1,1,1"]
|===
|Column name | Description | Type | Nullable

| `id` | Unique identifier for the patient in this system (not the NHS number or trust number) | UUID | No
| `first_name` | Patient's first or given name | String | Yes
| `last_name` | Patient's last or family name | String | Yes
| `date_of_birth` | Patient date of birth, to arbitrarily good resolution | Timestamp / datetime with timezone | Yes
| `gender` | Patient gender, one of 1 (male), 2 (female), 3 (non-binary), 4 (other, not listed), 255 (not stated), NULL (not recorded) (see https://digital.nhs.uk/data-and-information/data-collections-and-data-sets/data-sets/mental-health-services-data-set/submit-data/data-quality-of-protected-characteristics-and-other-vulnerable-groups/gender-identity[here], Table 3, gender identity as stated by person) | Byte | Yes
| `nhs_number` | Patient NHS number | String | Yes
| `trust_number` | Patient trust ID number  | String | Yes
| `created_at` | Time when this row was created | Timestamp / datetime with timezone | No
| `updated_at` | Time when this row was last updated | Timestamp / datetime with timezone | No
|===

NOTE: All these values can vary with time, either due to errors in recording or because they have really changed. This prototype of the program will not track changes or allow comments on the changes; these aspects should be incorporated into a production version of the program.
